version: '3'

services:
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    networks:
      - elk
  elastalert:
    build:
      context: elastalert/
    depends_on:
      - elk
    networks:
      - elk
    restart: always

networks:
  elk:
    driver: bridge
