version: '3'

services:
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elk
    restart: always
  heartbeat:
    build:
      context: heartbeat/
    depends_on:
      - elk
    networks:
      - elk
    restart: always
networks:
  elk:
    driver: bridge
